### ISSUE TITLE
[Bug] `Uint` does not implement correct `Encodable` trait

### ISSUE THREAD

**Issue by Wollac** [alloy-rs/core#191]
### Component

primitives

### What version of Alloy are you on?

alloy-primitives v0.2.0

### Operating System

macOS (Apple Silicon)

### Describe the bug

Using `RlpEncodable` to derive the RLP encoding of a struct containing `U256` fields from alloy-primitives v0.2.0 fails due to the correct trait not being implemented.
Rolling back to `v0.1.0` for all the alloy crates, fixes the problem and the same code compiles.

```rust
use alloy_primitives::U256;
use alloy_rlp::Encodable;
use alloy_rlp_derive::RlpEncodable;

#[derive(RlpEncodable)]
pub struct Test {
    pub value: U256
}
```

```toml
[dependencies]
alloy-primitives = { version = "0.2", features = ["rlp"] }
alloy-rlp = "0.2"
alloy-rlp-derive = "0.2"
```

**Comment by DaniPopes** [comment]
This is because `Uint` is from `ruint2`, which currently depends on `alloy-rlp v0.1.0`. Soon we'll release 0.3 and move from `ruint2` to `ruint`. For now you can import them with git:
```toml
[dependencies]
alloy-primitives = { git = "https://github.com/alloy-rs/core" }
alloy-rlp = { git = "https://github.com/alloy-rs/core" }
alloy-rlp-derive = { git = "https://github.com/alloy-rs/core" }
```
